### ISSUE TITLE
ValueError: "yolo3_tiny_darknet_coco" is not among the following model list:

### ISSUE THREAD

**Issue by kieven2008** [ElectronicElephant/tiny_yolov3#2]
ValueError: "yolo3_tiny_darknet_coco" is not among the following model list:

get_model会失败，因为它不在gluoncv的model_zoo里面
所以无法训练

**Comment by ElectronicElephant** [comment]
https://github.com/ElectronicElephant/tiny_yolov3/blob/e219cc1ffed04487d196a8835eee1d99d0c5e798/gluon-cv/gluoncv/model_zoo/model_zoo.py#L11

Do you have gluon-cv installed already?

If yes, please uninstall it first.

```
pip uninstall gluon-cv
```

Then, strictly follow the guide in [README](https://github.com/ElectronicElephant/tiny_yolov3#1-code).

**Comment by ElectronicElephant** [comment]
你好，

我估计是因为环境里已经安装了 gluoncv。先卸载掉，再按照首页的安装流程走一遍，应该就可以了。

**Comment by kieven2008** [comment]
> 你好，
> 
> 我估计是因为环境里已经安装了 gluoncv。先卸载掉，再按照首页的安装流程走一遍，应该就可以了。

Thank you for your quick response, I feel so appreciated for your help.
Yes, you are right, This project must use the local customized gluoncv.

**Comment by ElectronicElephant** [comment]
Cheers!
